# Rename this file to docker-compose.yaml
version: '3'
services:
  fermentrack:
    image: carjed/fermentrack-docker
    build: ./fermentrack
    container_name: fermentrack
    restart: always
    ports:
      - "81:8080"
    volumes:
        - ./volumes/db:/home/fermentrack/fermentrack/db
        - ./volumes/data:/home/fermentrack/fermentrack/data
        - ./volumes/log:/home/fermentrack/fermentrack/log
